version: "2"

services:
  db:
    image : mariadb:10.1.11 #4alldigital/drupalprod-mysql
    ports:
     - "3306"
    volumes :
      - mysql-data:/var/lib/mysql:rw
    env_file: mysql.env
    hostname: db
    restart: always
    networks:
      - data

  solr:
    image : 4alldigital/drupalprod-solr
    ports :
      - "8983"
    hostname: solr
    restart: always
    networks:
          - data
    networks:
      - data

  redis:
    image : 4alldigital/drupalprod-redis
    hostname: redis
    restart: always
    mem_limit: 1000000000
    memswap_limit: 2000000000
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /tmp/redis
      - /var/log/redis
    networks:
      - data

volumes:
  mysql-data:
    driver: local

networks:
  data:
    driver: bridge