dist: trusty
sudo: required

language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-dev

script:
  - ./scripts/basic.sh
  - sonar-scanner

notifications:
  slack:
    rooms:
      - 4alldigital:QY0MCk9HdP2Ls5nELR55lKNr
    on_success: change
    on_failure: change
  email: false
  
addons:
  sonarqube:
    organization: "dockerdrupal"
    token:
      secure: SONAR_TOKEN
    branches:
      - master
jdk:
  - oraclejdk8
  
cache:
  directories:
    - '$HOME/.sonar/cache'
