version: "3"

services:
  nginx-proxy:
    image: 4alldigital/drudock-nginx-proxy:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./mounts/proxy/certs:/etc/nginx/certs:ro
      - ./mounts/proxy/vhost.d:/etc/nginx/vhost.d
      - ./mounts/proxy/html:/usr/share/nginx/html
    hostname: nginx-proxy
    networks:
      - nginx
    restart: always
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"