version: '3'
services:

  auth_nginx:
    image: nginx:alpine
    container_name: nbcu_auth_nginx
    ports:
      - 8089:80
    volumes:
      - ./config/auth_nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ms-auth/src:/var/www:cached
    hostname: auth_nginx
    networks:
      - default
  auth_php:
    image: nbcuniversalpaint/ms-php:devtools
    volumes:
      - ./config/aws:/root/.aws/
      - ~/.ssh:/root/.ssh
      - ./ms-auth/src:/var/www:cached
    working_dir: /var/www/
    environment:
      - MYSQL_HOST=nbcu_mysql
      - MYSQL_DATABASE=auth
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
      - API_CONSUMER_BASE_URI_MESSAGING=http://messaging_nginx
    container_name: nbcu_auth_php
    hostname: auth_php
    networks:
      - default

  cms_middleware_nginx:
    image: nginx:alpine
    volumes:
      - ./config/cms_nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: nbcu_cms_middleware_nginx
    ports:
      - 8090:80
    hostname: cms_middleware_nginx
    networks:
      - default
  cms_middleware_php:
    image: nbcuniversalpaint/ms-php:devtools
    container_name: nbcu_cms_middleware_php
    environment:
      - API_ROUTE_PREFIX=
      - API_PROBLEM_DEBUG=true
      - MYSQL_HOST=nbcu_mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=cms
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
      - ELASTICSEARCH_HOST=nbcu_elasticsearch
      - ELASTICSEARCH_PORT=4571
      - CDN_WRAPPERS_HOST=d2350ndgykfz3k.cloudfront.net
    volumes:
      - ./ms-cms-middleware/src:/var/www:cached
    working_dir: /var/www/
    hostname: cms_middleware_php
    networks:
      - default

  est_nginx:
    image: nginx:alpine
    ports:
      - 8082:80
    volumes:
      - ./config/est_nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ms-est/src:/var/www:cached
    container_name: nbcu_est_nginx
    working_dir: /var/www/
    hostname: est_nginx
    networks:
      - default
  est_php:
    image: nbcuniversalpaint/ms-php:devtools
    volumes:
      - ./config/aws:/root/.aws/
      - ~/.ssh:/root/.ssh
      - ./config/aws:/var/www/.aws
      - ./ms-est/src/:/var/www:cached
    working_dir: /var/www/
    environment:
      - MYSQL_HOST=nbcu_mysql
      - MYSQL_DATABASE=est
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
      - API_CONSUMER_BASE_URI_MESSAGING=http://messaging_nginx
      - API_CONSUMER_BASE_URI_PAYMENTS=http://payments_nginx
      - ELASTICSEARCH_HOST=nbcu_elasticsearch
      - ELASTICSEARCH_PORT=4571
      - LOCALSTACK_S3_ENDPOINT=http://${UNWRAPT_DEV_HOST_ALIAS}:4572
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
    container_name: nbcu_est_php
    hostname: est_php
    networks:
      - default

  messaging_nginx:
    image: nginx:alpine
    ports:
      - 8084:80
    volumes:
      - ./config/messaging_nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ms-messaging/src:/var/www:cached
    container_name: nbcu_messaging_nginx
    hostname: messaging_nginx
    networks:
      - default
  messaging_php:
    image: nbcuniversalpaint/ms-php:devtools
    container_name: nbcu_messaging_php
    volumes:
      - ./config/aws:/root/.aws/
      - ./config/aws:/var/www/.aws
      - ./ms-messaging/src:/var/www:cached
    environment:
      - AWS_EMAIL_QUEUE_URL=http://${UNWRAPT_DEV_HOST_ALIAS}:4576/queue/emails_queue
    working_dir: /var/www/
    networks:
      - default

  payments_nginx:
    image: nginx:alpine
    ports:
      - 8086:80
    volumes:
      - ./config/payments_nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ms-payments/src:/var/www:cached
    container_name: nbcu_payments_nginx
    hostname: payments_nginx
    networks:
      - default
  payments_php:
    image: nbcuniversalpaint/ms-php:devtools
    volumes:
      - ./config/aws:/root/.aws/
      - ~/.ssh:/root/.ssh
      - ./ms-payments/src:/var/www:cached
    environment:
      - AWS_DYNAMODB_ENDPOINT=http://payments_dynamodb:4569
      - BRAINTREE_ENVIRONMENT=sandbox
      - BRAINTREE_MERCHANTID=8fwvzy5pbtq5vm9x
      - BRAINTREE_PUBLICKEY=ktx6m4dqjmmf6s6j
      - BRAINTREE_PRIVATEKEY=daedabdd6dacf10a7cb45a484366e7cd
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
    container_name: nbcu_payments_php
    working_dir: /var/www/
    hostname: payments_php
    networks:
      - default

  messaging_sqs:
    ports:
      - 7002:7002
      - 4576:4576
      - 4575:4575
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs
      - DATA_DIR=/tmp/sqs_new
      - DEFAULT_REGION=eu-west-1
      - PORT_WEB_UI=7002
      - HOSTNAME_EXTERNAL=${UNWRAPT_DEV_HOST_ALIAS}
      - HOSTNAME=${UNWRAPT_DEV_HOST_ALIAS}
      - DEBUG=1
    volumes:
      - ./config/aws:/root/.aws/
      - messaging-data:/tmp/sqs_new
    container_name: nbcu_messaging_sqs
    networks:
      - default
  payments_dynamodb:
    ports:
      - 4569:4569
    image: localstack/localstack:latest
    environment:
      - SERVICES=dynamodb
      - DATA_DIR=/tmp/dynamodb
    volumes:
      - dynamodb-data:/tmp/dynamodb
    container_name: nbcu_payments_dynamodb
    networks:
      - default
  est_s3:
    image: localstack/localstack:latest
    ports:
      - 7001:7001
      - 4572:4572
      - 4752:4752
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/s3
      - DEFAULT_REGION=eu-west-1
      - PORT_WEB_UI=7001
    volumes:
      - ./config/aws:/root/.aws/
      - s3-data:/tmp/s3
      - localstack-data:/tmp/localstack
    container_name: nbcu_est_s3
    networks:
      - default
  nbcu_elasticsearch:
    image: localstack/localstack:latest
    container_name: nbcu_elasticsearch
    environment:
      - SERVICES=es
      - DEFAULT_REGION=eu-west-1
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - PORT_WEB_UI=7003
      - DATA_DIR=/usr/share/elasticsearch/data
      - HOSTNAME_EXTERNAL=${UNWRAPT_DEV_HOST_ALIAS}
      - HOSTNAME=${UNWRAPT_DEV_HOST_ALIAS}
    ports:
      - 7003:7003
      - 5601:5601
      - 4571:4571
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - default

  nbcu_mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=est
      - MYSQL_USER=auth
      - MYSQL_PASSWORD=password
    container_name: nbcu_mysql
    hostname: nbcu_mysql
    networks:
      - default
  nbcu_mailhog:
    image: mailhog/mailhog
    container_name: nbcu_mailhog
    ports:
      - 8025:8025
    hostname: nbcu_mailhog
    networks:
      - default

  fe_middleware:
    image: unwraptfe
    ports:
      - 9002:80
      - 9001:9000
    volumes:
      - ./unwrapt-mw/:/app:consistent
    environment:
      - API_ES_PATH=http://nbcu_elasticsearch:4571
      - API_MS_KEY=D9Z9kQLfSf6XJyYL98UbiaJM7WmR0oq46vconFKM
      - API_PAYMENT_PATH=http://payments_nginx
      - API_AUTH_PATH=http://auth_nginx
      - API_EST_PATH=http://est_nginx
      - AUTH_USERNAME=middleware
      - AUTH_PASSWORD=tX9jhaEQovgojbii
      - NODE_ENV=development
      - PORT=9000
    command:
      - yarn
      - dev
    container_name: nbcu_fe_middleware
    hostname: fe_middleware
    networks:
      - default
  fe_site:
    image: unwraptfe
    ports:
      - 9011:80
      - 9010:3000
    volumes:
      - ./unwrapt-fe-site/:/app:consistent
    environment:
      - REACT_APP_MIDDLEWARE_API_PATH=http://${UNWRAPT_DEV_HOST_ALIAS}:9001
      - REACT_APP_MIDDLEWARE_API_KEY=8pdNM6J9Xg53ver8y7Ge43hs0gMg7aQA5Ii7jDMw
      - REACT_APP_LESS=true
      - REACT_APP_LESS_MODULES=true
      - FALLBACK_API_URL=http://${UNWRAPT_DEV_HOST_ALIAS}:9001
    command:
      - yarn
      - start
    container_name: nbcu_fe_site
    hostname: fe_site
    networks:
      - default

  fe_web_app:
    image: unwraptfe
    ports:
      - 9020:80
      - 9021:3000
      - 9022:3001
      - 9023:3002
    volumes:
      - ./unwrapt-web-app/:/app:consistent
    environment:
      - REACT_APP_MIDDLEWARE_API_PATH=http://${UNWRAPT_DEV_HOST_ALIAS}:9001
      - REACT_APP_MIDDLEWARE_API_KEY=8pdNM6J9Xg53ver8y7Ge43hs0gMg7aQA5Ii7jDMw
      - REACT_APP_LESS=true
      - REACT_APP_LESS_MODULES=true
      - FALLBACK_API_URL=http://${UNWRAPT_DEV_HOST_ALIAS}:9001
      - API_MIDDLEWARE_URL=http://${UNWRAPT_DEV_HOST_ALIAS}:9001
      - API_CLIENT_URL=http://${UNWRAPT_DEV_HOST_ALIAS}:9020
      - NODE_ENV=development
      - BROWSER=false
    command:
      - yarn
      - start
    container_name: nbcu_fe_web_app
    hostname: fe_web_app
    networks:
      - default

  fe_storybook:
    image: unwraptfe
    ports:
      - 9009:9009
    volumes:
      - ./unwrapt-fe-site/:/app:consistent
    environment:
      - REACT_APP_MIDDLEWARE_API_PATH=http://${UNWRAPT_DEV_HOST_ALIAS}:9001
      - REACT_APP_MIDDLEWARE_API_KEY=8pdNM6J9Xg53ver8y7Ge43hs0gMg7aQA5Ii7jDMw
      - REACT_APP_LESS=true
      - REACT_APP_LESS_MODULES=true
      - NODE_ENV=storybook
      - STORYBOOK_API_URL=http://${UNWRAPT_DEV_HOST_ALIAS}:9001
      - STORYBOOK_THEME=red
      - STORYBOOK_DATA_KEY=12345
      - STORYBOOK_FE_URL=http://${UNWRAPT_DEV_HOST_ALIAS}:9001
    command:
      - yarn
      - storybook
    container_name: nbcu_fe_storybook
    hostname: fe_storybook
    networks:
      - default
  fe_wrapping:
    image: unwraptfe
    ports:
      - 6007:6007
    volumes:
      - ./unwrapt-fe-wrapping/:/app:consistent
    environment:
      - NODE_ENV=storybook
    command:
      - yarn
      - storybook-dev
    container_name: nbcu_fe_wrapping
    hostname: fe_wrapping
    networks:
      - default

  sonarqube:
    image: 'sonarqube:6.6'
    volumes:
      - ./config/sonarqube/sonar.properties:/opt/sonarqube/conf/sonar.properties
      - ./config/sonarqube_extensions/:/opt/sonarqube/extensions/
      - sonarqube_data:/opt/sonarqube/data/
      - sonarqube_es_data:/opt/sonarqube/data/es5
      # - ./logs:/opt/sonarqube/logs
    ports:
      - '5001:9092'
      - '5002:9000'
    hostname: sonarqube
    container_name: nbcu_sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://sonarmysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    networks:
      - sonarnet
  sonarmysql:
    image: 'mysql:5.6'
    ports:
      - '3306'
    volumes:
      - 'sonarmysql-data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: rootsonar
      MYSQL_USER: sonar
      MYSQL_PASSWORD: sonar
      MYSQL_DATABASE: sonar
    hostname: sonarmysql
    container_name: nbcu_sonar_mysql
    healthcheck:
      test: 'exit 0'
    networks:
      - sonarnet

volumes:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_es_data:
  mysql-data:
    driver: local
  sonarmysql-data:
    driver: local
  dynamodb-data:
    driver: local
  elastic-data:
    driver: local
  s3-data:
    driver: local
  localstack-data:
    driver: local
  messaging-data:
    driver: local

networks:
  sonarnet:
    driver: bridge
  default:
    driver: bridge
